services:
  backend:
    build: ./backend
    image: furkanvka/club-backend:latest
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword

  frontend:
    build: ./frontend
    image: furkanvka/club-frontend:latest
    ports:
      - "3000:3000"
    restart: always

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
