spring:
  application:
    name: backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/mydb}
    username: ${SPRING_DATASOURCE_USERNAME:myuser}
    password: ${SPRING_DATASOURCE_PASSWORD:mypassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secret: "eW91ci12ZXJ5LXNlY3VyZS1hbmQtbG9uZy1qYXdhLXRva2VuLXNlY3JldC1rZXktZm9yLWRldmVsb3BtZW50" # base64 string for dev
    expiration-ms: 86400000 # 24 hours
